# Generated by Django 4.2.29 on 2026-08-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_coresettings_terminal_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="file_browser_mode",
            field=models.CharField(
                choices=[
                    ("new", "Use new file browser"),
                    ("legacy", "Use legacy file browser"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
