# Generated by Django 4.2.29 on 2026-07-27 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agents", "0062_agent_default_shell_agent_default_shell_custom"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileTransferSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("upload", "Upload"), ("download", "Download")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting_for_agent", "Waiting for agent"),
                            ("agent_ready", "Agent ready"),
                            ("transferring", "Transferring"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="waiting_for_agent",
                        max_length=32,
                    ),
                ),
                ("destination_path", models.CharField(max_length=4096)),
                ("filename", models.CharField(max_length=255)),
                (
                    "conflict_policy",
                    models.CharField(
                        choices=[("replace", "Replace"), ("skip", "Skip")],
                        default="replace",
                        max_length=16,
                    ),
                ),
                ("total_size", models.BigIntegerField()),
                ("chunk_size", models.PositiveIntegerField()),
                ("committed_offset", models.BigIntegerField(default=0)),
                ("last_ack_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("is_archive", models.BooleanField(default=False)),
                ("warnings", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_transfer_sessions",
                        to="agents.agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_transfer_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["agent", "status"],
                        name="agents_file_agent_i_30a6c8_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="agents_file_expires_922ac9_idx"
                    ),
                ],
            },
        ),
    ]
