# Generated by Django 4.2.29 on 2026-06-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_copy_mesh_permission_to_terminal"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_use_file_browser",
            field=models.BooleanField(default=False),
        ),
    ]
